from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class FuzzAction(BaseModel):
    """Represents a targeted boundary test action generated by the LLM."""
    selector: str = Field(description="CSS selector targeting the element (e.g., '#item-quantity', '#submit-order-btn').")
    action_type: Literal["fill", "click"] = Field(description="Action to perform: 'fill' for inputs, 'click' for buttons/links.")
    payload: Optional[str] = Field(default="", description="Input string payload for 'fill' action (e.g., '-10', '', '99999999').")
    rationale: str = Field(description="Rationale explaining the edge case or boundary condition being tested.")

class UXImprovement(BaseModel):
    """Represents a semantic, accessibility, or layout flaw detected in the DOM structure."""
    category: Literal["Accessibility", "Layout", "Usability", "Copywriting"] = Field(description="Category of the UX issue.")
    selector: str = Field(description="CSS selector of the affected element or container.")
    issue: str = Field(description="Clear description of the accessibility or UX design defect.")
    impact_rationale: str = Field(default="", description="Explanation of why this issue matters and the negative user impact, friction, or confusion it causes.")
    suggested_fix: str = Field(description="Concrete developer recommendation or code fix to resolve the issue.")

class AuditResponse(BaseModel):
    """Structured output expected from the LLM reasoning layer."""
    fuzz_actions: List[FuzzAction] = Field(description="List of targeted boundary test cases to execute.")
    ux_improvements: List[UXImprovement] = Field(description="List of detected UX and accessibility improvements.")

class HardBug(BaseModel):
    """Deterministic hard bug elevated strictly when Playwright intercepts a runtime error or 4xx/5xx response."""
    title: str
    severity: Literal["High", "Critical"] = "Critical"
    selector: str
    action_type: str
    payload: Optional[str] = None
    error_message: str
    status_code: Optional[int] = None
    reproduction_steps: List[str]
